**Gaussian Naive Bayes**

In [1]:
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB

In [2]:
import pandas as pd

In [13]:
iris = datasets.load_iris()
df_X=pd.DataFrame(iris.data)
df_Y=pd.DataFrame(iris.target)
dir(iris)

['DESCR',
 'data',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [12]:
df_X.head()

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

In [14]:
# model fitting
gnb = GaussianNB()
fitted = gnb.fit(iris.data,iris.target)
y_pred = fitted.predict(iris.data)

In [15]:
# check specific samples (1. probability)
fitted.predict_proba(iris.data)[[1,48,51,100]]

array([[1.00000000e+000, 1.51480769e-017, 2.34820051e-025],
       [1.00000000e+000, 2.63876217e-018, 2.79566024e-025],
       [7.27347795e-102, 9.45169639e-001, 5.48303606e-002],
       [3.23245181e-254, 6.35381031e-011, 1.00000000e+000]])

In [22]:
# 2. predict
fitted.predict(iris.data)[[1,48,51,100]]

array([0, 0, 1, 2])

In [23]:
# confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(iris.target,y_pred)

array([[50,  0,  0],
       [ 0, 47,  3],
       [ 0,  3, 47]])

In [24]:
# set a priori 1 
gnb2=GaussianNB(priors=[1/100,1/100,98/100]) # set the third priori large
fitted2=gnb2.fit(iris.data,iris.target)
y_pred2=fitted2.predict(iris.data)
confusion_matrix(iris.target,y_pred2) #wrong predict (2,3)

array([[50,  0,  0],
       [ 0, 33, 17],
       [ 0,  0, 50]])

In [26]:
# priori 2
gnb3=GaussianNB(priors=[1/100,98/100,1/100])
fitted3=gnb3.fit(iris.data,iris.target)
y_pred3=fitted2.predict(iris.data)
confusion_matrix(iris.target,y_pred3) #wrong predict (3,2)

array([[50,  0,  0],
       [ 0, 50,  0],
       [ 0, 14, 36]])

**Multinomial naive bayes**

In [27]:
from sklearn.naive_bayes import MultinomialNB
import numpy as np

In [29]:
X = np.random.randint(5, size=(6, 100)) # 6 samples, 100 variables
y = np.array([1, 2, 3, 4, 5, 6]) # 6-classes

In [30]:
clf = MultinomialNB()
clf.fit(X, y)

MultinomialNB()

In [32]:
print(clf.predict(X[2:3]))

[3]


In [34]:
# check probability
clf.predict_proba(X[2:3]) # probability of class3 is almost 1

array([[6.84484222e-34, 1.31198805e-32, 1.00000000e+00, 3.25135948e-33,
        1.45554434e-32, 2.85530104e-37]])

In [36]:
#change a priori
clf2 = MultinomialNB(class_prior=[0.1,0.5,0.1,0.1,0.1,0.1])
clf2.fit(X, y)

MultinomialNB(class_prior=[0.1, 0.5, 0.1, 0.1, 0.1, 0.1])

In [40]:
print(clf2.predict_proba(X[2:3]))
print(clf.predict(X[2:3])) #it is predicted to class3, 
#but the probability of class to is higher than before

[[6.84484222e-34 6.55994027e-32 1.00000000e+00 3.25135948e-33
  1.45554434e-32 2.85530104e-37]]
[3]
